
let movies = [
    {
        id: 1,
        "title": "Baazigar",
        "year": "1993",
        "genres": [
            "Crime",
            "Drama",
            "Musical"
        ],
        "ratings": [
            4,
            3,
            5,
            8,
            5,
            5,
            3,
            10,
            9,
            8,
            5,
            9,
            10,
            5,
            8,
            9,
            1,
            1,
            5,
            7,
            7,
            10,
            7,
            8,
            1,
            6,
            6,
            5,
            10,
            9
        ],
        "poster": "MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@.V1_SY250_CR0,0,187,250_AL.jpg",
        "contentRating": "",
        "duration": "PT175M",
        "releaseDate": "1993-11-12",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Widowed Madan Chopra lives a very wealthy lifestyle with two daughters, Seema and Priya. His passion is car racing, and realizing that he is not young anymore, has his last race and wins - only to find out that another competitor, Vicky Malhotra, let him win. Madan befriends Vicky, introduces him to Priya and invites him to work for him in Bombay. Vicky and Priya are attracted to each other, much to Madan's delight and he announces their marriage. Before that could happen, Seema kills herself by throwing herself down from the roof of a multi-storied building. While Madan wants to close this case due to embarrassment, Seema meets with her college friend, Police Inspector Karan, and together they begin to unravel a plot that may well end Madan and the lives of others as well.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Shah Rukh Khan",
            "Rakhee Gulzar",
            "Kajol"
        ],
        "imdbRating": 7.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTc3OTE1MDAxNV5BMl5BanBnXkFtZTgwNjM1NDk5NTE@._V1_SY250_CR0,0,187,250_AL_.jpg"
    },

    {
        id: 2,
        "title": "24",
        "year": "2016",
        "genres": [
            "Action",
            "Romance",
            "Sci-Fi"
        ],
        "ratings": [
            5,
            1,
            5,
            1,
            3,
            9,
            3,
            2,
            8,
            6,
            7,
            2,
            9,
            9,
            9,
            10,
            6,
            5,
            1,
            10,
            7,
            4,
            5,
            8,
            6,
            2,
            4,
            10,
            9,
            6
        ],
        "poster": "MV5BZmYyNWRmNjUtODg5OC00YmRjLTkwYWMtMjY5NjA5ZjhkNDg3XkEyXkFqcGdeQXVyNDA1NTY2Nzk@.V1_SY500_CR0,0,333,500_AL.jpg",
        "contentRating": "",
        "duration": "PT164M",
        "releaseDate": "2016-05-06",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A Sci-Fi family revenge drama happening between a scientist, his evil brother and the scientist's son, over a time travel gadget.                Written by\nNaveen Sankaran",
        "actors": [
            "Suriya",
            "Samantha Ruth Prabhu",
            "Nithya Menon"
        ],
        "imdbRating": 8.0,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZmYyNWRmNjUtODg5OC00YmRjLTkwYWMtMjY5NjA5ZjhkNDg3XkEyXkFqcGdeQXVyNDA1NTY2Nzk@._V1_SY500_CR0,0,333,500_AL_.jpg"
    },

    {
        id: 3,
        "title": "Jodhaa Akbar",
        "year": "2008",
        "genres": [
            "Action",
            "Adventure",
            "Biography"
        ],
        "ratings": [
            7,
            2,
            3,
            8,
            6,
            1,
            4,
            2,
            1,
            10,
            6,
            3,
            7,
            4,
            4,
            1,
            3,
            9,
            5,
            10,
            2,
            6,
            9,
            1,
            3,
            7,
            9,
            7,
            3,
            9
        ],
        "poster": "MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@.V1_SY361_SX250_AL.jpg",
        "contentRating": "",
        "duration": "PT213M",
        "releaseDate": "2008-02-15",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Jodhaa Akbar is a sixteenth century love story about a marriage of alliance that gave birth to true love between a great Mughal Emperor, Akbar and a Rajput princess, Jodhaa. Politically, success knew no bounds for Emperor Akbar, After having secured the Hindu Kush, he furthered his realm by conquest until his empire extended from Afghanistan to the Bay of Bengal, and from the Himalayas to the Godhavari River. Through a shrewd blend of tolerance, generosity and force, Akbar won the allegiance of the Rajputs, the most belligerent Hindus. But little did Akbar know that when he married Jodhaa, a fiery Rajput princess, in order to further strengthen his relations with the Rajputs, he would in turn be embarking upon a new journey - the journey of true love. The daughter of King Bharmal of Amer, Jodhaa resented being reduced to a mere political pawn in this marriage of alliance, and Akbar's biggest challenge now did not merely lie in winning battles, but in winning the love of Jodhaa - a ...                Written by\nhEmRaJ (gavin_coolhgr@hotmail.com)",
        "actors": [
            "Hrithik Roshan",
            "Aishwarya Rai Bachchan",
            "Sonu Sood"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI1ODQ2MDIxMl5BMl5BanBnXkFtZTcwNTc3Mzk1MQ@@.V1_SY361_SX250_AL.jpg"
    },

    {
        id: 4,
        "title": "Wake Up Sid",
        "year": "2009",
        "genres": [
            "Comedy",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            7,
            10,
            6,
            7,
            3,
            3,
            1,
            4,
            10,
            2,
            6,
            3,
            6,
            1,
            6,
            7,
            8,
            4,
            10,
            9,
            10,
            4,
            6,
            2,
            5,
            6,
            2,
            4
        ],
        "poster": "MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@.V1_SY489_SX324_AL.jpg",
        "contentRating": "",
        "duration": "PT138M",
        "releaseDate": "2009-10-02",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In Mumbai, Sid Mehra is, in the words of his father, an arrogant, spoiled brat. He lives with a doting mother, subservient brother, and a father who covers his expenses and credit card bills. Sid takes his college finals then starts work at his father's business; he lasts less than a week before walking out. At a graduation party, he meets Aisha, newly arrived from Calcutta and set on becoming a writer. He shows her the city and helps her refurbish a rented flat. He asks if she'd like to progress from friend to something more, but she says no: he lacks ambition and isn't her type. Will her words, his exam results, a confrontation with his parents, and a break with his friends be enough to wake Sid up?                Written by\n<jhailey@hotmail.com>",
        "actors": [
            "Ranbir Kapoor",
            "Konkona Sen Sharma",
            "Supriya Pathak"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTg2NTk2MjU5NV5BMl5BanBnXkFtZTcwNTY0Nzg4Mg@@.V1_SY489_SX324_AL.jpg"
    },

    {
        id: 5,
        "title": "Saala Khadoos",
        "year": "2016",
        "genres": [
            "Action",
            "Drama",
            "Sport"
        ],
        "ratings": [
            2,
            3,
            7,
            2,
            7,
            2,
            2,
            10,
            1,
            2,
            7,
            6,
            4,
            2,
            2,
            1,
            6,
            3,
            4,
            2,
            2,
            2,
            3,
            5,
            7,
            10,
            7,
            8,
            3,
            10
        ],
        "poster": "MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@.V1_SY334_SX250_AL.jpg",
        "contentRating": "",
        "duration": "PT109M",
        "releaseDate": "2016-01-29",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "An under-fire boxing coach, Prabhu is transferred from Hisar in Haryana to Chennai as his bosses at the Boxing Council do not like his disrespectful rule-breaking unconventional ways. In Chennai, he chances upon the raw fighting talent of Madhi, the sibling of aspiring boxer Lakshmi. He decides to put all his effort to tame Madhie and get her to shine but he is repeatedly put off by her playfulness & distrust.                Written by\nPipingHotViews",
        "actors": [
            "Madhavan",
            "Nassar",
            "Radha Ravi"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BM2Q5YmM3YjMtOTE2Mi00MDg5LThkZjctYzUxOWU2ZTM1ZDk4XkEyXkFqcGdeQXVyMTExNDQ2MTI@.V1_SY334_SX250_AL.jpg"
    },

    {
        id: 6,
        "title": "Qayamat Se Qayamat Tak",
        "year": "1988",
        "genres": [
            "Action",
            "Drama",
            "Musical"
        ],
        "ratings": [
            5,
            2,
            10,
            3,
            2,
            5,
            8,
            1,
            4,
            5,
            3,
            6,
            9,
            8,
            9,
            9,
            8,
            4,
            10,
            2,
            1,
            1,
            5,
            9,
            3,
            1,
            9,
            8,
            8,
            7
        ],
        "poster": "MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@.V1_SY250_SX168_AL.jpg",
        "contentRating": "",
        "duration": "PT162M",
        "releaseDate": "1988-03-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Both Dhanraj Singh and Randhir Singh are two bitter and old time enemies. They faced a disastrous situation when there children, Raj and Rashmi falls deeply in love. They openly declares there hatred for one another and will do anything in there power even kill but they will not accept there children's choice. But Raj and Rashmi is dedicated to there love and is not willing to accept the fact that there dads are enemies.                Written by\ngAvInDrA (brave_loverboy2004@hotmail.com)",
        "actors": [
            "Aamir Khan",
            "Juhi Chawla",
            "Goga Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTY4MDQyMDUzOF5BMl5BanBnXkFtZTcwMjUyNTAzMQ@@.V1_SY250_SX168_AL.jpg"
    },

    {
        id: 7,
        "title": "Delhi Belly",
        "year": "2011",
        "genres": [
            "Comedy",
            "Crime",
            "Drama"
        ],
        "ratings": [
            10,
            9,
            8,
            4,
            3,
            1,
            4,
            4,
            4,
            1,
            1,
            4,
            4,
            3,
            2,
            9,
            6,
            3,
            6,
            8,
            2,
            8,
            2,
            4,
            10,
            4,
            5,
            6,
            3,
            2
        ],
        "poster": "MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@.V1_SY360_SX250_AL.jpg",
        "contentRating": "",
        "duration": "PT103M",
        "releaseDate": "2011-07-01",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Delhi-based Sonia agrees to deliver a package for Vladimir Dragunsky and asks her rather unkempt and debt-ridden fianc\u00e9, Tashi Malhotra, to do it for her. Tashi, in turn, asks one of two of his room-mates, Nitin. But Nitin forgets to do so due to an upset stomach ailment commonly known as 'Delhi Belly' as well as his plan to blackmail their landlord, Manish and asks the third roommate Arup to deliver the package. A gangster, Somayajulu, who was the recipient of this package, starts by brutally questioning Vladimir, and finds out that the package may be in the possession of the trio. While Tashi must deal with his attraction for Journalist Menaka and incur the wrath of her husband, Rajiv, he still has to fully come to terms whether or not he wants to marry Sonia. And the entry of ruthless Somayajulu and his gang seriously jeopardizes any plans Tashi and his friends may have for the future.                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Imran Khan",
            "Vir Das",
            "Kunaal Roy Kapur"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNTI3ODQwNDAzN15BMl5BanBnXkFtZTcwMDg5NDExNg@@.V1_SY360_SX250_AL.jpg"
    },
    {
        id: 8,
        "title": "Magadheera",
        "year": "2009",
        "genres": [
            "Action",
            "Drama",
            "Romance"
        ],
        "ratings": [
            10,
            9,
            2,
            8,
            4,
            9,
            1,
            9,
            7,
            8,
            1,
            4,
            10,
            3,
            7,
            2,
            1,
            2,
            1,
            3,
            1,
            8,
            9,
            4,
            1,
            9,
            10,
            9,
            10,
            9
        ],
        "poster": "MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@.V1_SY500_CR0,0,333,500_AL.jpg",
        "contentRating": "",
        "duration": "PT147M",
        "releaseDate": "2009-07-30",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "In 1609 AD, Mitravinda, a princess, and Kala Bhairava, the warrior that she loved, die. 400 years later, the warrior is reincarnated as Harsha, a motorcycle stuntman. He brushes hands with a girl and sparks fly as he begins to recall his past life. Knowing that he is destined to love this young woman, he sets about trying to identify her. Indu does not remember her past life and keeps Harsha at a distance; playing tricks on him until she gets to know him better. However, just as the two begin to fall in love, a sinister force from their shared past returns!                Written by\nL. Hamre",
        "actors": [
            "Kajal Aggarwal",
            "Dev Gill",
            "Srihari"
        ],
        "imdbRating": 7.7,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BNzQxNWE0NjctMzgxZC00NTdlLTkxMWUtNGM1MmRiYjM4ZWIwXkEyXkFqcGdeQXVyNjQ2MjQ5NzM@.V1_SY500_CR0,0,333,500_AL.jpg"
    },
    {
        id: 9,
        "title": "Highway",
        "year": "2014",
        "genres": [
            "Adventure",
            "Drama",
            "Romance"
        ],
        "ratings": [
            3,
            6,
            8,
            8,
            5,
            2,
            8,
            10,
            8,
            8,
            8,
            1,
            4,
            2,
            5,
            5,
            7,
            6,
            10,
            9,
            10,
            3,
            5,
            4,
            8,
            5,
            1,
            4,
            5,
            1
        ],
        "poster": "MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@.V1_SY500_CR0,0,344,500_AL.jpg",
        "contentRating": "",
        "duration": "PT133M",
        "releaseDate": "2014-02-21",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A city girl - young, full of life - is on the highway at night with her fianc\u00e9. Suddenly, her life is swung away from the brocade and jewelry of marriage to the harsh brutality of abduction. Her life will never be the same again. The gang is in a panic; the girl is a big industrialist's daughter, his links in the corridors of power make ransom out of the question. But for the leader of this group sending her back is not an option. As the days pass by, the scenery changes, the girl feels that she has changed as well. Gradually, a strange bond begins to develop between the victim and the oppressor. It is in this captivity that she, for the first time, feels free.                Written by\nVikram Nayak",
        "actors": [
            "Alia Bhatt",
            "Randeep Hooda",
            "Durgesh Kumar"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMjE5NjkyNTczM15BMl5BanBnXkFtZTgwNDg4MzE5MDE@.V1_SY500_CR0,0,344,500_AL.jpg"
    },
    {
        id: 10,
        "title": "Aankhen",
        "year": "2002",
        "genres": [
            "Comedy",
            "Thriller",
            "Crime"
        ],
        "ratings": [
            6,
            9,
            1,
            10,
            7,
            2,
            6,
            2,
            5,
            10,
            8,
            4,
            4,
            4,
            3,
            1,
            7,
            4,
            2,
            7,
            8,
            4,
            1,
            10,
            10,
            1,
            1,
            4,
            1,
            1
        ],
        "poster": "MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@.V1_SY500_SX345_AL.jpg",
        "contentRating": "",
        "duration": "PT165M",
        "releaseDate": "2002-04-05",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Vijay Singh Rajput (Amitabh Bachchan) is a quirky manager of Vilasrao Jefferson Bank. He is extremely strict at work and believes in pushing his workers to the limit. This means that his superiors hold him in high regard for his unblemished reputation and excellent track record. But things go terribly wrong for the honest bank manager when he finds one of his own employees trying to con the customers. At this, he loses his temper and gets physical with the employee. This doesn't go down well with his superiors and they decide that Rajput is now a liability to the bank and they sack him. Amitabh can't believe the Board of Directors and his mind is filled with revenge and what better revenge than robbing the bank himself, ironic as it may sound. He decides that he must think of a plan that will hit the bank where it hurts the most - in its safe where all the money is kept. Rajput blackmails Neha (Sushmita Sen) to use her professional skills to help his plan, to train three blind men to ...                Written by\nAnonymous",
        "actors": [
            "Amitabh Bachchan",
            "Akshay Kumar",
            "Sushmita Sen"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BYmE2MTNkYTctN2FjYS00Zjc2LWFiOGQtNzFmZmE4YzM2NmM4XkEyXkFqcGdeQXVyNDUzOTQ5MjY@.V1_SY500_SX345_AL.jpg"
    },
    {
        id: 11,
        "title": "Rockstar",
        "year": "2011",
        "genres": [
            "Drama",
            "Music",
            "Musical"
        ],
        "ratings": [
            7,
            9,
            2,
            7,
            4,
            2,
            2,
            9,
            10,
            10,
            6,
            9,
            10,
            2,
            6,
            3,
            6,
            9,
            2,
            7,
            10,
            10,
            4,
            9,
            2,
            9,
            9,
            2,
            6,
            10
        ],
        "poster": "MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@.V1_SY500_SX375_AL.jpg",
        "contentRating": "",
        "duration": "PT159M",
        "releaseDate": "2011-11-11",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The film follows Janardhan Jhakar in a series of flashbacks and flash forwards, how the small collage boy became an international rock sensation \"Jordan\". To chase his dreams of a rockstar, the wanna-be singer his counseled that music and feelings only come with pain. In the process of which, he meets Heer, a tough on the outside and popular college girl, the both become friends, and as time passes by his dreams of music fade away as they spend time together. When heer moves away, Janardhan is thrown out of his house because of family misunderstandings. As he bides his time at a local mosque, his passion for music comes back to life. He is soon signed by a record label, where he makes more enemies than friends, his tour takes him to Prague, where he is reunited with a married Heer. Things go awry when the two share an intimate moment, and Jordan his deported to India on trespassing charges filed by Heer's husband. Now an angry painful and lonely JORDAN embarks on his journey to become...                Written by\nEros International",
        "actors": [
            "Ranbir Kapoor",
            "Nargis Fakhri",
            "Shammi Kapoor"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BOTc3NzAxMjg4M15BMl5BanBnXkFtZTcwMDc2ODQwNw@@.V1_SY500_SX375_AL.jpg"
    },
    {
        id: 12,
        "title": "Piku",
        "year": "2015",
        "genres": [
            "Comedy",
            "Drama"
        ],
        "ratings": [
            4,
            1,
            4,
            5,
            1,
            5,
            6,
            10,
            5,
            5,
            10,
            9,
            7,
            8,
            1,
            8,
            7,
            1,
            10,
            6,
            7,
            8,
            2,
            2,
            10,
            10,
            9,
            1,
            1,
            3
        ],
        "poster": "MV5BMTUwOTMxNjc2OV5BMl5BanBnXkFtZTgwODQ4OTMxNTE@.V1_SY500_SX375_AL.jpg",
        "contentRating": "",
        "duration": "PT123M",
        "releaseDate": "2015-05-08",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "A quirky comedy about the relationship between a daughter and her aging father, whose eccentricities drive everyone crazy.",
        "actors": [
            "Amitabh Bachchan",
            "Deepika Padukone",
            "Irrfan Khan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTUwOTMxNjc2OV5BMl5BanBnXkFtZTgwODQ4OTMxNTE@.V1_SY500_SX375_AL.jpg"
    },
    {
        id: 13,
        "title": "Socha Na Tha",
        "year": "2005",
        "genres": [
            "Romance",
            "Comedy"
        ],
        "ratings": [
            6,
            7,
            4,
            3,
            4,
            8,
            6,
            1,
            7,
            1,
            3,
            7,
            1,
            6,
            8,
            6,
            5,
            10,
            5,
            2,
            8,
            8,
            5,
            1,
            7,
            1,
            1,
            10,
            2,
            10
        ],
        "poster": "MV5BMzMwNDcwNTAyOF5BMl5BanBnXkFtZTcwOTg2ODgzMQ@@.V1_SY250_CR0,0,176,250_AL.jpg",
        "contentRating": "",
        "duration": "PT137M",
        "releaseDate": "2005-03-04",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Mr. Oberoi is a wealthy industrialist, and lives a comfortable lifestyle, with this two sons. The elder son is married, and Mr Oberoi wants his second son, Viren, to marry too. He has already selected a bride for him in Aditi Malhotra. Though Viren has always lived in his father and brother's shadows, he is quite romantic at heart, and hopes to fall in love first and then marry the girl of his choice. The presence of Aditi prevents this, and he makes all attempts not to marry her. He succeeds, the wedding arrangements are all called off. Then he meets the girl of his dreams, Karen Fernandes, and proposes marriage to her. The only setback he sees that she is a Catholic, and he, a Hindu. However, that is soon overcome. Everything seems to go on smoothly between both the families, when Viren falls out of love with Karen, and wants to cancel the wedding. When questioned about his change in mind, he responds that he is in love with Aditi. But Aditi will not have anything to do with him ...                Written by\nrAjOo (gunwanti@hotmail.com)",
        "actors": [
            "Abhay Deol",
            "Ayesha Takia",
            "Ayesha Jhulka"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMzMwNDcwNTAyOF5BMl5BanBnXkFtZTcwOTg2ODgzMQ@@.V1_SY250_CR0,0,176,250_AL.jpg"
    },
    {
        id: 14,
        "title": "Dil Se..",
        "year": "1998",
        "genres": [
            "Drama",
            "Romance"
        ],
        "ratings": [
            10,
            6,
            2,
            1,
            5,
            2,
            9,
            5,
            2,
            4,
            2,
            5,
            4,
            5,
            4,
            5,
            6,
            5,
            4,
            10,
            2,
            1,
            10,
            1,
            6,
            1,
            7,
            5,
            9,
            1
        ],
        "poster": "MV5BMTI2NjU4MjkxOF5BMl5BanBnXkFtZTcwMTc3MDYxMQ@@.V1_SY237_CR0,0,165,237_AL.jpg",
        "contentRating": "",
        "duration": "PT163M",
        "releaseDate": "1998-08-21",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Amar Varma, a producer for Indian news radio, meets an enigmatic woman at a railroad station and then again at a hill station. He falls in love with her, but the woman, who calls herself Meghna, rejects and leaves him although she seems to be interested. Later, Varma agrees to marry his family's choice, Preeti. But suddenly Meghna is back, and what is the secret that she holds?                Written by\n<sunilm@nwu.edu>",
        "actors": [
            "Shah Rukh Khan",
            "Manisha Koirala",
            "Preity Zinta"
        ],
        "imdbRating": 7.8,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTI2NjU4MjkxOF5BMl5BanBnXkFtZTcwMTc3MDYxMQ@@.V1_SY237_CR0,0,165,237_AL.jpg"
    },
    {
        id: 15,
        "title": "Devdas",
        "year": "2002",
        "genres": [
            "Musical",
            "Romance"
        ],
        "ratings": [
            1,
            6,
            6,
            7,
            8,
            5,
            1,
            1,
            4,
            7,
            1,
            9,
            9,
            6,
            5,
            2,
            10,
            5,
            9,
            7,
            1,
            8,
            3,
            4,
            7,
            1,
            10,
            6,
            3,
            7
        ],
        "poster": "MV5BY2QxMGM4Y2QtMGFmMy00ZjZkLWExMWQtNTY1Yjc0MDFjZjY0XkEyXkFqcGdeQXVyNTE0MDc0NTM@.V1_SY500_CR0,0,345,500_AL.jpg",
        "contentRating": "",
        "duration": "PT185M",
        "releaseDate": "2002-07-12",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "The son of Zamindar Narayan Mukherjee, Devdas (Shahrukh Khan) was born with a silver spoon in his mouth. He grew up in the lush village of Taj Sonapur, where he spent his childhood, indulged by his lovely playmate Paro (Aishwarya). They grew up sharing a special relationship, in which they existed only to each other. Oblivious of all the differences of status and background, a bond that would never break grew between them. Slowly, it changed to love but it was still unsaid. But the reverie was broken when his family sent Devdas to London for education. Paro's world crashed knowing that her Devdas would be gone and she lit a diya, for it signified the fast coming back of her loved one. Years passed and Devdas returned. Devdas was besotted by her stunning beauty and longed to have her back. But Zamindar Narayan Mukherjee (Vijay Crishna), Devdas' father, met Paro's mother Sumitra's (Kiran Kher) marriage proposal with condescending arrogance. It caused a rift between the families and even...                Written by\nAnonymous",
        "actors": [
            "Shah Rukh Khan",
            "Madhuri Dixit",
            "Aishwarya Rai Bachchan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BY2QxMGM4Y2QtMGFmMy00ZjZkLWExMWQtNTY1Yjc0MDFjZjY0XkEyXkFqcGdeQXVyNTE0MDc0NTM@.V1_SY500_CR0,0,345,500_AL.jpg"
    },
    {
        id: 16,
        "title": "Hum Aapke Hain Koun...!",
        "year": "1994",
        "genres": [
            "Comedy",
            "Drama",
            "Musical"
        ],
        "ratings": [
            10,
            3,
            10,
            6,
            8,
            7,
            6,
            9,
            5,
            10,
            4,
            5,
            6,
            6,
            3,
            8,
            8,
            7,
            8,
            2,
            10,
            7,
            1,
            8,
            1,
            5,
            10,
            5,
            9,
            10
        ],
        "poster": "MV5BMTcwMjk5NDg1Nl5BMl5BanBnXkFtZTgwMjA2NTkwMzE@.V1_SY250_CR0,0,187,250_AL.jpg",
        "contentRating": "",
        "duration": "PT206M",
        "releaseDate": "1994-08-05",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "Prem, a top student, is learning the ropes of business under his elder brother Rajesh and his uncle Kailashnath, a big industrialist. In another town, Nisha is studying computer science and is the darling of her elder sister, Pooja, and her parents, Professor Choudhry and Kamladevi. Fate brings the two families together and this results in the the betrothal of Rajesh and Pooja. At the wedding, Prem meets Nisha and falls in love with this carefree woman. With Pooja as the woman of the house, joy knows no bounds in Prem's family. Months pass by and Pooja becomes pregnant. Nisha is invited to come and stay with her sister and attend the traditional function before the child's birth. Nisha's arrival is like a dream come true for Prem. Nisha stays there until the birth of the child, taking over the household chores, and becoming very much a part of the family. In soft whispers, Prem and Nisha commit their love for each other and secretly dream of spending a lifetime together. Then fate ...                Written by\nSujit R. Varma",
        "actors": [
            "Madhuri Dixit",
            "Salman Khan",
            "Mohnish Bahl"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BMTcwMjk5NDg1Nl5BMl5BanBnXkFtZTgwMjA2NTkwMzE@.V1_SY250_CR0,0,187,250_AL.jpg"
    },
    {
        id: 17,
        "title": "Hum Dil De Chuke Sanam",
        "year": "1999",
        "genres": [
            "Comedy",
            "Drama",
            "Musical"
        ],
        "ratings": [
            5,
            9,
            2,
            4,
            1,
            2,
            10,
            5,
            7,
            3,
            3,
            10,
            10,
            6,
            2,
            8,
            1,
            9,
            6,
            8,
            10,
            8,
            3,
            3,
            7,
            6,
            1,
            8,
            2,
            5
        ],
        "poster": "MV5BZWI5ZWMxN2QtNjJmNS00M2EwLTg3ZmUtYzI5ODY3MWM2MzM1XkEyXkFqcGdeQXVyNDk3Mzg2OTc@.V1_SY500_CR0,0,350,500_AL.jpg",
        "contentRating": "",
        "duration": "PT188M",
        "releaseDate": "1999-06-18",
        "averageRating": 0,
        "originalTitle": "",
        "storyline": "When Sameer asks for Nandini's hand in marriage her family refuses. They have already chosen a husband for their daughter. Sameer returns to Italy. When Vanraj, Nandini's husband realizes that his new bride has been in love with someone else, he is prepared to sacrifice his love for her and take her to Italy to be reunited with her true love, Sameer.                Written by\nTapestry",
        "actors": [
            "Salman Khan",
            "Ajay Devgn",
            "Aishwarya Rai Bachchan"
        ],
        "imdbRating": 7.6,
        "posterurl": "https://images-na.ssl-images-amazon.com/images/M/MV5BZWI5ZWMxN2QtNjJmNS00M2EwLTg3ZmUtYzI5ODY3MWM2MzM1XkEyXkFqcGdeQXVyNDk3Mzg2OTc@.V1_SY500_CR0,0,350,500_AL.jpg"
    },

]
